version: '3.8'

services:
 
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
        - "11143:1433"
        volumes:
        - C:\Docker\DockerVolumes\sqlserver:/var/opt/mssql/data 
        networks:
            - mydbnet
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
networks:
    mydbnet: