FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
 
FROM fluffybunny4/build AS build
WORKDIR /src
RUN dotnet publish  ./src/Apps/TokenService -c Release -o /out --no-restore --no-build
RUN ls

FROM base AS final
WORKDIR /app

# copy the SSL certificate
ADD cert/* /tmp/cert/
RUN apt-get install ca-certificates 
RUN cp -R /tmp/cert/cosmos-host.docker.internal.cer /usr/local/share/ca-certificates 
RUN update-ca-certificates

COPY --from=build /out .
ENV ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
ENTRYPOINT ["dotnet", "TokenService.dll"]