version: '3.8'

services:
  sampleexternalservice:
    image: ghstahl/sampleexternalservice:latest
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 7300:80
      - 7301:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=7301
