version: '3.8'

services:
  fluffybunnyadmin:
    image: ghstahl/fluffybunny.admin:latest
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 7200:80
      - 7201:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=7201
      - BLAH_ConnectionStrings__DefaultConnection=Server=(host.docker.internal)\\mssqllocaldb;Database=aspnet-FluffyBunny.Admin-53bc9b9d-9d6a-45d4-8429-2a2761773502;Trusted_Connection=True;MultipleActiveResultSets=true
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,11143;Database=myDataBase;User Id=sa;password=Your_password123;Trusted_Connection=False;MultipleActiveResultSets=true
      - EntityFrameworkConnectionOptions__ConnectionString=Server=host.docker.internal,11143;Database=fluffybunny;User Id=sa;password=Your_password123;Trusted_Connection=False;MultipleActiveResultSets=true
      - EntityFrameworkConnectionOptions__ConnectionStringDatabaseTemplate=Server=host.docker.internal,11143;Database={{Database}};User Id=sa;password=Your_password123;Trusted_Connection=False;MultipleActiveResultSets=true


 