# Stage 1
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build

WORKDIR /src
COPY . .



RUN find -type d -name bin -prune -exec rm -rf {} \; && find -type d -name obj -prune -exec rm -rf {} \;
RUN dotnet restore ./FluffyBunny.IdentityServer.sln
RUN dotnet build   ./FluffyBunny.IdentityServer.sln -c Debug --no-restore
RUN dotnet test    ./FluffyBunny.IdentityServer.sln -c Debug --no-restore --no-build
RUN dotnet build   ./FluffyBunny.IdentityServer.sln -c Release --no-restore
