version: '3.8'

services:
  sqlserver-microservice:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        ports:
        - "11143:1433"
        volumes:
        - C:\Docker\DockerVolumes\sqlserver:/var/opt/mssql/data 

  fluffybunnyadmin-microservice:
    image: ghstahl/fluffybunny.admin:latest
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 7200:80
      - 7201:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=7201
      - BLAH_ConnectionStrings__DefaultConnection=Server=(sqlserver-microservice)\\mssqllocaldb;Database=aspnet-FluffyBunny.Admin-53bc9b9d-9d6a-45d4-8429-2a2761773502;Trusted_Connection=True;MultipleActiveResultSets=true
      - ConnectionStrings__DefaultConnection=Server=sqlserver-microservice;Database=myDataBase;User Id=sa;password=Your_password123;Trusted_Connection=False;MultipleActiveResultSets=true
      - EntityFrameworkConnectionOptions__ConnectionString=Server=sqlserver-microservice;Database=fluffybunny;User Id=sa;password=Your_password123;Trusted_Connection=False;MultipleActiveResultSets=true
      - EntityFrameworkConnectionOptions__ConnectionStringDatabaseTemplate=Server=sqlserver-microservice;Database={{Database}};User Id=sa;password=Your_password123;Trusted_Connection=False;MultipleActiveResultSets=true
      - externalOIDC__0__authority=https://demo.identityserver.io/
      - externalOIDC__0__clientId=interactive.confidential
      - externalOIDC__0__clientSecret=secret
      - externalOIDC__0__callbackPath=/signin-demo-identityserver
      - externalOIDC__1__authority=${externalOIDC__1__authority}
      - externalOIDC__1__clientId=${externalOIDC__1__clientId}
      - externalOIDC__1__clientSecret=${externalOIDC__1__clientSecret}    
    depends_on:
      - sqlserver-microservice

  externalservice-microservice:
    image: ghstahl/sampleexternalservice:latest
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 7300:80
      - 7301:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=7301

  identityserverhost-microservice:
    image: ghstahl/identityserverhost:latest
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 7400:80
      - 7401:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=7401

  tokenservice-microservice:
    image: ghstahl/tokenservice:latest
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 7000:80
      - 7001:443
    depends_on:
      - identityserverhost-microservice
      - sqlserver-microservice
    environment:
      - Logging__LogLevel__Default=Debug
      - AppOptions__DisableHttpRedirect=true
      - AppOptions__OperationalStoreType=EntityFramework
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=7001
      - ARM_CLIENT_ID=${ARM_CLIENT_ID}
      - ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET}
      - ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID}
      - ARM_TENANT_ID=${ARM_TENANT_ID}
      - KeyVaultSigningOptions__KeyVaultName=kv-fluffybunny4
      - CosmosDbConfiguration__DangerousAcceptAnyServerCertificateValidator=true
      - CosmosDbConfiguration__EndPointUrl=https://host.docker.internal:8081
      - CosmosDbConfiguration__PrimaryKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
      - AZURE_CosmosDbConfiguration__EndPointUrl=https://fluffybunny4.documents.azure.com:443
      - AZURE_CosmosDbConfiguration__PrimaryKey=**REDACTED**
      - BLAH_ConnectionStrings__DefaultConnection=Server=(sqlserver-microservice)\\mssqllocaldb;Database=aspnet-FluffyBunny.Admin-53bc9b9d-9d6a-45d4-8429-2a2761773502;Trusted_Connection=True;MultipleActiveResultSets=true
      - ConnectionStrings__DefaultConnection=Server=sqlserver-microservice;Database=myDataBase;User Id=sa;password=Your_password123;Trusted_Connection=False;MultipleActiveResultSets=true
      - EntityFrameworkConnectionOptions__ConnectionString=Server=sqlserver-microservice;Database=fluffybunny;User Id=sa;password=Your_password123;Trusted_Connection=False;MultipleActiveResultSets=true
      - EntityFrameworkConnectionOptions__ConnectionStringDatabaseTemplate=Server=sqlserver-microservice;Database={{Database}};User Id=sa;password=Your_password123;Trusted_Connection=False;MultipleActiveResultSets=true

  webappexternallogin-microservice:
    image: ghstahl/webappexternallogin:latest
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 44299:80
      - 44300:443
    environment:
      - externalOIDC__0__authority=https://demo.identityserver.io/
      - externalOIDC__0__clientId=interactive.confidential
      - externalOIDC__0__clientSecret=secret
      - externalOIDC__0__callbackPath=/signin-demo-identityserver
      - externalOIDC__1__authority=${externalOIDC__1__authority}
      - externalOIDC__1__clientId=${externalOIDC__1__clientId}
      - externalOIDC__1__clientSecret=${externalOIDC__1__clientSecret}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=44300

 
  oidcconsentorchestrator-microservice:
    image: ghstahl/oidcconsentorchestrator:latest
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    ports:
      - 56600:80
      - 56601:443
    environment:
      - AppOptions__DangerousAcceptAnyServerCertificateValidator=true
      - Logging__LogLevel__Default=Debug    
      - oidcOptionStore__Google__clientRecords__0__ClientId=${oidcOptionStore__Google__clientRecords__0__ClientId}
      - oidcOptionStore__Google__clientRecords__0__Secret=${oidcOptionStore__Google__clientRecords__0__Secret}
      - FluffyBunny4TokenServiceConfiguration__ClientId=301e4b53-27c2-4508-86f7-448f08229a44
      - FluffyBunny4TokenServiceConfiguration__ClientSecret=NkFzuAe3V8LL4PHSjuPCPCRE5HXQ53bq
      - FluffyBunny4TokenServiceConfiguration__Authority=https://host.docker.internal:7001/zep
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
      - ASPNETCORE_HTTPS_PORT=6601
    networks:
      - local
   
networks:
  local:
    driver: bridge
    
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup: